### ISSUE TITLE
Example midifile_dump.cpp is missing math.h and iostream includes

### ISSUE THREAD

**Issue by pissalou** [celtera/libremidi#113]
The example does not compile due to missing include math.h for pow() function.
It is also missing iostream (mispelled istream).

**Comment by jcelerier** [comment]
strange, on which platform are you ? the CI builds the examples on pretty much every platform and this hasn't come up

**Comment by pissalou** [comment]
I'm on ubuntu 23.04, cmake v3.25.1, make 4.3, gcc 12.3.0.
This seems like this is an issue only on the 4.X branch, I forgot to mention.

**Comment by jcelerier** [comment]
ohh ok

**Comment by jcelerier** [comment]
pushed both fixes there
