### ISSUE TITLE
garbage value in message size when used in flatpak

### ISSUE THREAD

**Issue by shriramters** [celtera/libremidi#121]
I recently packaged my app that uses libremidi with flatpak.

I am using libremidi 4.5.0

the `libremidi::message`  parameter in the on_message callback of a `midi_in` object has correct values but the message size is a garbage number.

```c++
    libremidi::midi_in midiin{{
        .on_message =
            [&](const libremidi::message& message) {
                    if((int)message.get_message_type() == 0x90) {
                        std::cout << message.size() << std::endl;
                        std::cout << (int)message[0] << " " << (int) message[1] << " " << (int) message[2] << std::endl;
                    }
                
            },
       .on_error = [] (libremidi::midi_error code, std::string_view info){

           std::cerr << "ERR:" << code << " " << info << std::endl;
            },
        .ignore_sysex = false,
        .ignore_timing = false,
        .ignore_sensing = false,
        }};
```

## output

I pressed the note C and released it

```
140463348648915
144 60 74
140463348648915
144 60 0
```

Everything else is correct. Just the size is a huge value.

This only occurs in the flatpak version of my app

**Comment by shriramters** [comment]
it is using the ALSA_SEQ backend. Not sure if this is relevant

**Comment by shriramters** [comment]
I have made a minimal reproducible example here ; https://github.com/shriramters/bugremidi

In https://github.com/shriramters/bugremidi/commit/062903da99f81ae80d45ecc4ce526efbb9672978 the issue does not occur 

*message size output without boost:*
```
shriram@think182:~/Workspace/bug.libremidi$ flatpak run bug.libremidi.bugremidi
PORT YAMAHA Portatone MIDI 1 connected : true opened : true

Reading MIDI input ... play a note to see the error. press <enter> to quit.
3
3
3
3

```

but when boost is installed, (https://github.com/shriramters/bugremidi/commit/8d11a15024ca702ec9aaa51deb6e2ec1935b248c) then the size is a garbage value

*message size output with boost:*
```
shriram@think182:~/Workspace/bug.libremidi$ flatpak run bug.libremidi.bugremidi
PORT YAMAHA Portatone MIDI 1 connected : true opened : true

Reading MIDI input ... play a note to see the error. press <enter> to quit.
140495829338993
140495829338993
140495829338993
140495829338993
```

**Comment by jcelerier** [comment]
Heya !
My hunch is that the compiled version of libremidi uses boost::small_vector for libremidi::message but not your app. A quick fix would be to pass -DLIBREMIDI_NO_BOOST=1 to cmake when building libremidi

**Comment by shriramters** [comment]
Yes that does indeed fix the issue in my app! Thanks!

**Comment by shriramters** [comment]
In my flatpak manifest, I am first installing libremidi to the machine, then installing boost and then compiling my app (Same as the reproducible example). 

I had a hunch that if boost is installed before libremidi, it might not cause the issue

I just confirmed that.

https://github.com/shriramters/bugremidi/commit/0877c59cb9466fd2a719a962e44ac22bbc04130c

Here Boost is installed first. This fixes the issue too.

**Comment by jcelerier** [comment]
yep - note that this has been fixed in 5.x though, there just hasn't been a release yet as I want to wait for the official Windows MIDI 2 support

**Comment by shriramters** [comment]
Thanks for your help.
> note that this has been fixed in 5.x 

That's great! I am closing the issue in that case

Looking forward to v5
